import { PricingPlan } from "./types";

export const tiers: PricingPlan[] = [
  {
    id: 0,
    name: "Starter",
    type: "standard",
    priceId: {
      month: "pri_01k27ajepm199twd1x77rpwdrq",
      year: "pri_01k27ajepm199twd1x77rpwdrq",
    },
    description:
      "Perfect for individuals and small businesses getting started.",
    features: {
      support: "Email support",
      catalogues: 1,
      newsletter: false,
      ocr_ai_import: 0,
      traffic_limit: 500,
      branding: false,
      custom_features: false,
      analytics: "Basic",
      ai_prompts: 0,
      categories_per_catalogue: 3,
      items_per_catalogue: 15,
    },
  },
  {
    id: 1,
    name: "Basic",
    type: "standard",
    priceId: {
      month: "pri_01k7bm6p3pnskk0k71akh10mp5",
      year: "pri_01k7bme4em8fr22gztzeayny74",
    },
    description: "Perfect fit for small businesses to digitalize their offer.",
    features: {
      support: "Email support",
      catalogues: 1,
      newsletter: false,
      ocr_ai_import: 0,
      traffic_limit: 2000,
      branding: true,
      custom_features: false,
      analytics: "Basic",
      ai_prompts: 0,
      categories_per_catalogue: 6,
      items_per_catalogue: 30,
    },
  },
  {
    id: 2,
    name: "Pro",
    type: "standard",
    priceId: {
      month: "pri_01k277hdtkkb1xdbz6karkqek9",
      year: "pri_01k277q6ftcjfzy9v7xhe6ckdt",
    },
    description: "Ideal for growing businesses with multiple services.",
    features: {
      support: "Email support",
      catalogues: 6,
      newsletter: false,
      ocr_ai_import: 0,
      traffic_limit: 5000,
      branding: true,
      custom_features: false,
      analytics: "Basic",
      ai_prompts: 10,
      categories_per_catalogue: 15,
      items_per_catalogue: 100,
    },
  },
  {
    id: 3,
    name: "Growth",
    type: "standard",
    priceId: {
      month: "pri_01k277kkzqz4ef7nc786ssnw6x",
      year: "pri_01k277r7p899gfn5nn3ne87pww",
    },
    description: "Built for teams that need advanced features and analytics.",
    features: {
      support: "Email & Chat support",
      catalogues: 20,
      newsletter: true,
      ocr_ai_import: 10,
      traffic_limit: 15000,
      branding: true,
      custom_features: false,
      analytics: "Advanced",
      ai_prompts: 25,
      categories_per_catalogue: 30,
      items_per_catalogue: 200,
    },
  },
  {
    id: 4,
    name: "Premium",
    type: "standard",
    priceId: {
      month: "pri_01k277mzp3tgy7n5wvrsa5v0sx",
      year: "pri_01k277see7qtyq30kc5g3vyqy9",
    },
    description: "Enterprise-grade solution with unlimited possibilities.",
    features: {
      support: "Priority Support (Email, Chat, Meeting)",
      catalogues: 50,
      newsletter: true,
      ocr_ai_import: 20,
      traffic_limit: 40000,
      branding: true,
      custom_features: true,
      analytics: "Advanced",
      ai_prompts: 50,
      categories_per_catalogue: 50,
      items_per_catalogue: 300,
    },
  },
  {
    id: 5,
    name: "German Silva Custom Plan",
    type: "custom",
    priceId: {
      month: "pri_01k81jpe1487tnvtr4gzmd9jmq",
      year: "pri_01k81jpe1487tnvtr4gzmd9jmq",
    },
    description: "Custom plan tailored for needs of German Silva.",
    features: {
      support: "Email",
      catalogues: 1,
      newsletter: false,
      ocr_ai_import: 0,
      traffic_limit: 4000,
      branding: true,
      custom_features: false,
      analytics: "Basic",
      ai_prompts: 0,
      categories_per_catalogue: 20,
      items_per_catalogue: 200,
    },
  },
];
